# Generated by Django 4.1.2 on 2022-10-22 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('town', models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, default='Canada', max_length=100, null=True, verbose_name='Country')),
                ('uni', models.CharField(blank=True, max_length=100, null=True, verbose_name='University')),
                ('student_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acc', models.CharField(blank=True, max_length=20, null=True)),
                ('pubkey', models.CharField(blank=True, max_length=200, null=True)),
                ('privatekey', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profiles',
                'ordering': ['-timestamp'],
            },
        ),
    ]
